openapi: 3.0.0
info:
  title: User API (Frontend Reference)
  version: 1.0.0

paths:
  /users:
    get:
      summary: Fetch all users
      responses:
        200:
          description: Successful response
    post:
      summary: Add new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
